#!/bin/sh

rm -rf .release/

stack install rumpus:rumpus --local-bin-path=.release

mkdir -p .release/packages/mingw/bin
mkdir -p .release/packages/snapshot
mkdir -p .release/packages/local

echo "Compiling fake GCC..."
ghc util/fakeGCC.hs -o .release/packages/mingw/bin/gcc.exe

echo "Copying package dbs..."

echo "Copying snapshot package db..."
result=`stack path --snapshot-install-root`; snapshot_install_root=${result%pkgdb}
cp -R $snapshot_install_root/lib .release/packages/snapshot
cp -R $snapshot_install_root/pkgdb .release/packages/snapshot

echo "Copying local package db..."
result=`stack path --local-install-root`; local_install_root=${result%pkgdb}
cp -R $local_install_root/lib .release/packages/local
cp -R $local_install_root/pkgdb .release/packages/local

result=`stack path --global-pkg-db`; global_pkg_db_path=${result%package.conf.d}
cp -R $global_pkg_db_path .release/packages/

echo "Copying resources..."
cp -r resources/ .release/
cp -r scenes/ .release/

echo "Copying dlls..."
cp `which libfreetype-6.dll` .release
cp `which libpd.dll` .release
cp `which libwinpthread-1.dll` .release
cp `which OpenAL32.dll` .release
cp `which openvr_api.dll` .release
cp `which libstdc++-6.dll` .release
cp `which libbz2-1.dll` .release
cp `which libharfbuzz-0.dll` .release
cp `which zlib1.dll` .release
cp `which libpng16-16.dll` .release
cp `which libgcc_s_seh-1.dll` .release
cp `which libglib-2.0-0.dll` .release
cp `which libintl-8.dll` .release
cp `which libiconv-2.dll` .release